/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2019-12-31 05:14:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>관리자 페이지</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("        * {padding: 0; margin: 0; position: relative; box-sizing: border-box;}\r\n");
      out.write("        body,html {width: 100%; height: 100%; margin: 0; padding: 0;}\r\n");
      out.write("        .wrap {width: 360px; height: 640px; margin: 0 auto; }\r\n");
      out.write("        \r\n");
      out.write("        /*root*/\r\n");
      out.write("        .head {width: 100%; height: 50px; background: #E8B963; }\r\n");
      out.write("        .head>h1 { margin: 0 auto; text-align: center; line-height: 50px; font-weight: 100;}\r\n");
      out.write("        .head>span {color: white; right: 10px; font-size: 18px; position: absolute; top: 0; line-height: 50px; cursor: pointer;}\r\n");
      out.write("        \r\n");
      out.write("        /*back*/\r\n");
      out.write("        .section1 {width: 100%; height: 120px; display: flex; align-items: center;}\r\n");
      out.write("        .section1>span {width: 100%; line-height: 120px; position: absolute; top: 0; font-size: 18px; transform: rotateY(180deg); left: -330px; cursor: pointer;}\r\n");
      out.write("\r\n");
      out.write("        /*AD*/\r\n");
      out.write("        .section2 {width: 100%; height: 80px; background: #d2d2d2;}\r\n");
      out.write("        .section2>p {width: 100%; line-height: 80px; position: absolute; top: 0; left: 30px;}\r\n");
      out.write("        \r\n");
      out.write("        /*user & CEO*/\r\n");
      out.write("        .section3 {width: 100%; height: 150px; display: flex; align-items: center; justify-content: center; border-bottom: 3px solid #d2d2d2;}\r\n");
      out.write("        .section3>div {width: 40%; display: flex; align-items: center; justify-content: center; flex-direction: column;}\r\n");
      out.write("        .section3>div>div {width: 100%;  height: 40px; background: darkred; display: flex; align-items: center; justify-content: center; }\r\n");
      out.write("        .section3 .user>div {color: white; border-radius: 10px 0px 0px 10px; cursor: pointer;}\r\n");
      out.write("        .section3 .ceo>div {color: white; border-radius: 0px 10px 10px 0px;  cursor: pointer;}\r\n");
      out.write("        .section3>div>div>span {line-height: 30px; }\r\n");
      out.write("        .section3 .user p {margin: 0;  cursor: pointer;}\r\n");
      out.write("        .section3 .ceo p {margin: 0; cursor: pointer;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("        <header class=\"head\">\r\n");
      out.write("                <h1>root</h1>\r\n");
      out.write("                <span class=\"glyphicon glyphicon-cog\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </header>\r\n");
      out.write("        <section class=\"section section1\">\r\n");
      out.write("            <span class=\"glyphicon glyphicon-share-alt\" aria-hidden=\"true\"></span>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"section section2\">\r\n");
      out.write("            <p>AD</p>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"section section3\">\r\n");
      out.write("            <div class=\"user\">\r\n");
      out.write("                <div>\r\n");
      out.write("                  <span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>User</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ceo\">\r\n");
      out.write("                <div>\r\n");
      out.write("                   <span class=\"glyphicon glyphicon-home\"  aria-hidden=\"true\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>CEO</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
